// ──────────────────────────────────────────────
// DesignTokens.swift
// Auto-generated by @sebellds/tokens – do not edit.
// Source: packages/tokens/dist/tokens.json (sebell × default).
// Run `npm run tokens:build` to regenerate.
// ──────────────────────────────────────────────

import SwiftUI

// MARK: - Colors
extension Color {
    static let surfacePrimaryLightest = Color(red: 0.459, green: 0.639, blue: 0.475)
    static let surfacePrimaryLighter = Color(red: 0.400, green: 0.600, blue: 0.416)
    static let surfacePrimaryLight = Color(red: 0.361, green: 0.541, blue: 0.376)
    static let surfacePrimaryMain = Color(red: 0.278, green: 0.420, blue: 0.290)
    static let surfacePrimaryDark = Color(red: 0.200, green: 0.302, blue: 0.208)
    static let surfacePrimaryDarker = Color(red: 0.122, green: 0.180, blue: 0.125)
    static let surfacePrimaryDarkest = Color(red: 0.078, green: 0.122, blue: 0.082)
    static let surfaceSecondaryLightest = Color(red: 0.788, green: 0.749, blue: 0.714)
    static let surfaceSecondaryLighter = Color(red: 0.745, green: 0.698, blue: 0.655)
    static let surfaceSecondaryLight = Color(red: 0.702, green: 0.651, blue: 0.596)
    static let surfaceSecondaryMain = Color(red: 0.576, green: 0.502, blue: 0.424)
    static let surfaceSecondaryDark = Color(red: 0.459, green: 0.400, blue: 0.341)
    static let surfaceSecondaryDarker = Color(red: 0.404, green: 0.349, blue: 0.298)
    static let surfaceSecondaryDarkest = Color(red: 0.345, green: 0.302, blue: 0.255)
    static let surfaceNeutralWhite = Color(red: 0.984, green: 0.984, blue: 0.976)
    static let surfaceNeutralLightest = Color(red: 0.965, green: 0.957, blue: 0.937)
    static let surfaceNeutralLighter = Color(red: 0.925, green: 0.910, blue: 0.875)
    static let surfaceNeutralLight = Color(red: 0.890, green: 0.867, blue: 0.812)
    static let surfaceNeutralMain = Color(red: 0.851, green: 0.824, blue: 0.749)
    static let surfaceNeutralDark = Color(red: 0.741, green: 0.690, blue: 0.561)
    static let surfaceNeutralDarker = Color(red: 0.667, green: 0.600, blue: 0.431)
    static let surfaceNeutralDarkest = Color(red: 0.631, green: 0.557, blue: 0.369)
    static let successLightest = Color(red: 0.925, green: 0.910, blue: 0.875)
    static let successLighter = Color(red: 0.890, green: 0.867, blue: 0.812)
    static let successLight = Color(red: 0.816, green: 0.776, blue: 0.686)
    static let successMain = Color(red: 0.361, green: 0.541, blue: 0.376)
    static let successDark = Color(red: 0.278, green: 0.420, blue: 0.290)
    static let successDarker = Color(red: 0.122, green: 0.180, blue: 0.125)
    static let successDarkest = Color(red: 0.078, green: 0.122, blue: 0.082)
    static let successContrastText = Color(red: 0.984, green: 0.984, blue: 0.976)
    static let errorLightest = Color(red: 0.984, green: 0.937, blue: 0.914)
    static let errorLighter = Color(red: 0.969, green: 0.871, blue: 0.831)
    static let errorLight = Color(red: 0.910, green: 0.616, blue: 0.490)
    static let errorMain = Color(red: 0.678, green: 0.286, blue: 0.122)
    static let errorDark = Color(red: 0.510, green: 0.216, blue: 0.090)
    static let errorDarker = Color(red: 0.341, green: 0.145, blue: 0.059)
    static let errorDarkest = Color(red: 0.169, green: 0.071, blue: 0.031)
    static let errorContrastText = Color(red: 0.984, green: 0.984, blue: 0.976)
    static let infoLightest = Color(red: 0.933, green: 0.961, blue: 0.965)
    static let infoLighter = Color(red: 0.871, green: 0.922, blue: 0.929)
    static let infoLight = Color(red: 0.612, green: 0.769, blue: 0.788)
    static let infoMain = Color(red: 0.349, green: 0.616, blue: 0.651)
    static let infoDark = Color(red: 0.278, green: 0.490, blue: 0.522)
    static let infoDarker = Color(red: 0.141, green: 0.247, blue: 0.259)
    static let infoDarkest = Color(red: 0.071, green: 0.122, blue: 0.129)
    static let infoContrastText = Color(red: 0.039, green: 0.059, blue: 0.043)
    static let warningLightest = Color(red: 0.965, green: 0.957, blue: 0.937)
    static let warningLighter = Color(red: 0.925, green: 0.910, blue: 0.875)
    static let warningLight = Color(red: 0.851, green: 0.824, blue: 0.749)
    static let warningMain = Color(red: 0.776, green: 0.733, blue: 0.624)
    static let warningDark = Color(red: 0.706, green: 0.643, blue: 0.494)
    static let warningDarker = Color(red: 0.667, green: 0.600, blue: 0.431)
    static let warningDarkest = Color(red: 0.631, green: 0.557, blue: 0.369)
    static let warningContrastText = Color(red: 0.039, green: 0.059, blue: 0.043)
    static let textPrimary = Color(red: 0.039, green: 0.059, blue: 0.043)
    static let textSecondary = Color(red: 0.459, green: 0.400, blue: 0.341)
    static let textBrand = Color(red: 0.239, green: 0.361, blue: 0.251)
    static let textLight = Color(red: 0.278, green: 0.420, blue: 0.290)
    static let textLighter = Color(red: 0.361, green: 0.541, blue: 0.376)
    static let textContrastText = Color(red: 0.984, green: 0.984, blue: 0.976)
    static let iconBrand = Color(red: 0.278, green: 0.420, blue: 0.290)
    static let iconAccent = Color(red: 0.576, green: 0.502, blue: 0.424)
    static let iconPrimary = Color(red: 0.039, green: 0.059, blue: 0.043)
    static let iconSecondary = Color(red: 0.459, green: 0.400, blue: 0.341)
    static let iconLight = Color(red: 0.278, green: 0.420, blue: 0.290)
    static let iconLighter = Color(red: 0.361, green: 0.541, blue: 0.376)
    static let iconContrast = Color(red: 0.984, green: 0.984, blue: 0.976)
    static let borderLight = Color(red: 0.890, green: 0.867, blue: 0.812)
    static let borderDefault = Color(red: 0.776, green: 0.733, blue: 0.624)
    static let borderDark = Color(red: 0.706, green: 0.643, blue: 0.494)
    static let borderHover = Color(red: 0.631, green: 0.557, blue: 0.369)
    static let borderActive = Color(red: 0.278, green: 0.420, blue: 0.290)
    static let componentsFocusRingDefault = Color(red: 0.278, green: 0.420, blue: 0.290)
    static let componentsFocusRingError = Color(red: 0.678, green: 0.286, blue: 0.122)
    static let componentsButtonBackgroundEnabled = Color(red: 0.278, green: 0.420, blue: 0.290)
    static let componentsButtonBackgroundHover = Color(red: 0.400, green: 0.600, blue: 0.416)
    static let componentsButtonBackgroundPressed = Color(red: 0.200, green: 0.302, blue: 0.208)
    static let componentsButtonOutlineBackgroundHover = Color(red: 0.400, green: 0.600, blue: 0.416)
    static let componentsButtonOutlineBackgroundPressed = Color(red: 0.361, green: 0.541, blue: 0.376)
    static let componentsButtonBorderEnabled = Color(red: 0.278, green: 0.420, blue: 0.290)
    static let componentsButtonBorderHover = Color(red: 0.400, green: 0.600, blue: 0.416)
    static let componentsButtonBorderPressed = Color(red: 0.200, green: 0.302, blue: 0.208)
    static let componentsButtonTextEnabled = Color(red: 0.984, green: 0.984, blue: 0.976)
    static let componentsButtonTextHover = Color(red: 0.039, green: 0.059, blue: 0.043)
    static let componentsButtonTextPressed = Color(red: 0.984, green: 0.984, blue: 0.976)
    static let componentsFormsSurfaceActive = Color(red: 0.278, green: 0.420, blue: 0.290)
    static let componentsFormsSurfaceEnabled = Color(red: 0.667, green: 0.600, blue: 0.431)
    static let componentsFormsSurfaceHover = Color(red: 0.200, green: 0.302, blue: 0.208)
    static let componentsFormsSurfacePressed = Color(red: 0.122, green: 0.180, blue: 0.125)
    static let componentsFormsSurfaceError = Color(red: 0.678, green: 0.286, blue: 0.122)
    static let componentsFormsBorderEnabled = Color(red: 0.776, green: 0.733, blue: 0.624)
    static let componentsFormsBorderHover = Color(red: 0.200, green: 0.302, blue: 0.208)
    static let componentsFormsBorderFocused = Color(red: 0.278, green: 0.420, blue: 0.290)
    static let componentsFormsBorderPressed = Color(red: 0.122, green: 0.180, blue: 0.125)
    static let componentsFormsBorderError = Color(red: 0.678, green: 0.286, blue: 0.122)
    static let componentsFormsBorderSubdued = Color(red: 0.890, green: 0.867, blue: 0.812)
    static let componentsFormsBackgroundDefault = Color(red: 0.965, green: 0.957, blue: 0.937)
    static let componentsFormsBackgroundActive = Color(red: 0.984, green: 0.984, blue: 0.976)
    static let componentsFormsBackgroundPressed = Color(red: 0.890, green: 0.867, blue: 0.812)
    static let componentsFormsBackgroundOff = Color(red: 0.925, green: 0.910, blue: 0.875)
    static let componentsChipBackgroundEnabled = Color(red: 0.345, green: 0.302, blue: 0.255)
    static let componentsChipBackgroundHover = Color(red: 0.404, green: 0.349, blue: 0.298)
    static let componentsChipBackgroundPressed = Color(red: 0.459, green: 0.400, blue: 0.341)
    static let componentsChipTextEnabled = Color(red: 0.984, green: 0.984, blue: 0.976)
    static let componentsChipTextHover = Color(red: 0.984, green: 0.984, blue: 0.976)
    static let componentsChipTextPressed = Color(red: 0.984, green: 0.984, blue: 0.976)
    static let componentsChipActiveBackgroundEnabled = Color(red: 0.278, green: 0.420, blue: 0.290)
    static let componentsChipActiveBackgroundHover = Color(red: 0.361, green: 0.541, blue: 0.376)
    static let componentsChipActiveBackgroundPressed = Color(red: 0.200, green: 0.302, blue: 0.208)
    static let componentsChipActiveTextEnabled = Color(red: 0.984, green: 0.984, blue: 0.976)
    static let componentsChipActiveTextHover = Color(red: 0.039, green: 0.059, blue: 0.043)
    static let componentsChipActiveTextPressed = Color(red: 0.984, green: 0.984, blue: 0.976)
    static let componentsTabBarActiveBackgroundEnabled = Color(red: 0.278, green: 0.420, blue: 0.290)
    static let componentsTabBarActiveBackgroundPressed = Color(red: 0.200, green: 0.302, blue: 0.208)
    static let componentsTabBarActiveTextEnabled = Color(red: 0.984, green: 0.984, blue: 0.976)
    static let componentsTabBarActiveTextPressed = Color(red: 0.984, green: 0.984, blue: 0.976)
}

// MARK: - Radius
enum DSRadius {
    static let none: CGFloat = 0
    static let xsmall: CGFloat = 0
    static let small: CGFloat = 0
    static let medium: CGFloat = 0
    static let large: CGFloat = 0
    static let xlarge: CGFloat = 0
    static let full: CGFloat = 8000
}

// MARK: - Spacing
enum DSSpacing {
    enum Layout {
        static let xxsmall: CGFloat = 4
        static let xsmall: CGFloat = 8
        static let small: CGFloat = 16
        static let medium: CGFloat = 24
        static let large: CGFloat = 40
        static let xlarge: CGFloat = 64
        static let xxlarge: CGFloat = 104
    }
    enum Components {
        static let xxsmall: CGFloat = 2
        static let xsmall: CGFloat = 4
        static let small: CGFloat = 8
        static let medium: CGFloat = 12
        static let large: CGFloat = 16
        static let xlarge: CGFloat = 24
        static let xxlarge: CGFloat = 32
        static let xxxlarge: CGFloat = 40
    }
}

// MARK: - Font Sizes
enum DSFontSize {
    static let display1: CGFloat = 72
    static let display2: CGFloat = 56
    static let display3: CGFloat = 44
    static let display4: CGFloat = 32
    static let display5: CGFloat = 24
    static let display6: CGFloat = 16
    static let paragraph: CGFloat = 16
    static let small: CGFloat = 12
    static let componentsLabel: CGFloat = 14
    static let componentsTableHeader: CGFloat = 16
    static let componentsButtonLabel: CGFloat = 16
}

// MARK: - Line Heights
enum DSLineHeight {
    static let xxlarge: CGFloat = 88
    static let xlarge: CGFloat = 72
    static let large: CGFloat = 56
    static let medium: CGFloat = 40
    static let small: CGFloat = 32
    static let xsmall: CGFloat = 24
    static let xxsmall: CGFloat = 16
}

// MARK: - Font Weights
enum DSFontWeight {
    static let emphasized: Font.Weight = .bold
    static let `default`: Font.Weight = .regular
    static let understate: Font.Weight = .light
}

// MARK: - Font Families
enum DSFontFamily {
    static let header: String = "Noto Serif"
    static let paragraph: String = "Noto Sans"
}

