/**
 * generate-swift.mjs
 * Reads the flat JSON output from Style Dictionary and generates
 * a Swift file with typed token constants for iOS / SwiftUI.
 *
 * Run: node transforms/generate-swift.mjs
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";

const tokens = JSON.parse(readFileSync("output/tokens.json", "utf-8"));

const lines = [
  "// ──────────────────────────────────────────────",
  "// Auto-generated by @ds/tokens — do not edit.",
  "// ──────────────────────────────────────────────",
  "",
  "import SwiftUI",
  "",
];

// ── Helpers ──────────────────────────────────────

function swiftName(path) {
  return path
    .map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1)))
    .join("");
}

function walk(obj, path = []) {
  const entries = [];
  for (const [key, val] of Object.entries(obj)) {
    if (val && typeof val === "object" && "value" in val) {
      entries.push({ path: [...path, key], value: val.value, type: val.type });
    } else if (val && typeof val === "object") {
      entries.push(...walk(val, [...path, key]));
    }
  }
  return entries;
}

// ── Color extension ──────────────────────────────

const colors = walk(tokens).filter(
  (t) => t.type === "color" || t.path[0] === "color"
);

if (colors.length) {
  lines.push("// MARK: - Colors", "extension Color {");
  for (const { path, value } of colors) {
    const hex = value.replace("#", "");
    const r = parseInt(hex.substring(0, 2), 16) / 255;
    const g = parseInt(hex.substring(2, 4), 16) / 255;
    const b = parseInt(hex.substring(4, 6), 16) / 255;
    const name = swiftName(path.slice(1)); // drop "color" prefix
    lines.push(
      `    static let ${name} = Color(red: ${r.toFixed(3)}, green: ${g.toFixed(3)}, blue: ${b.toFixed(3)})`
    );
  }
  lines.push("}", "");
}

// ── Spacing ──────────────────────────────────────

const spacings = walk(tokens).filter((t) => t.path[0] === "spacing");

if (spacings.length) {
  lines.push("// MARK: - Spacing", "enum DSSpacing {");
  for (const { path, value } of spacings) {
    const name = `space${path[path.length - 1]}`;
    const px = parseFloat(value) * (value.includes("rem") ? 16 : 1);
    lines.push(`    static let ${name}: CGFloat = ${px}`);
  }
  lines.push("}", "");
}

// ── Radius ───────────────────────────────────────

const radii = walk(tokens).filter((t) => t.path[0] === "radius");

if (radii.length) {
  lines.push("// MARK: - Border Radius", "enum DSRadius {");
  for (const { path, value } of radii) {
    const name = path[path.length - 1];
    const px =
      value === "9999px"
        ? 9999
        : parseFloat(value) * (value.includes("rem") ? 16 : 1);
    lines.push(`    static let ${name}: CGFloat = ${px}`);
  }
  lines.push("}", "");
}

// ── Font sizes ───────────────────────────────────

const fontSizes = walk(tokens).filter(
  (t) => t.path[0] === "font" && t.path[1] === "size"
);

if (fontSizes.length) {
  lines.push("// MARK: - Font Sizes", "enum DSFontSize {");
  for (const { path, value } of fontSizes) {
    const name = path[path.length - 1];
    const px = parseFloat(value) * 16;
    lines.push(`    static let ${name}: CGFloat = ${px}`);
  }
  lines.push("}", "");
}

// ── Write ────────────────────────────────────────
// The iOS Swift Package (packages/ios-tokens) expects the generated
// file at its own ./output/DesignTokens.swift. We're running from
// packages/tokens, so write up-and-over into the sibling package.

const outDir = "../ios-tokens/output";
mkdirSync(outDir, { recursive: true });
writeFileSync(`${outDir}/DesignTokens.swift`, lines.join("\n"));
console.log(`✓ ${outDir}/DesignTokens.swift generated`);
