// swift-tools-version: 5.9
// ──────────────────────────────────────────────
// DSTokens – Auto-generated design tokens for iOS / SwiftUI.
// Sources/DSTokens/DesignTokens.swift is generated by
// packages/tokens/transforms/generate-swift.mjs and committed to git,
// because SwiftPM consumes packages straight from the repository.
// Run `npm run tokens:build` to regenerate – never edit it by hand.
// ──────────────────────────────────────────────

import PackageDescription

let package = Package(
    name: "DSTokens",
    platforms: [
        .iOS(.v16),
        .macOS(.v13)
    ],
    products: [
        .library(
            name: "DSTokens",
            targets: ["DSTokens"]
        )
    ],
    targets: [
        .target(
            name: "DSTokens"
        )
    ]
)
